### PR TITLE
Add support for script[src] and link[rel=import]

### PR DESCRIPTION
**Pull request by valpackett**
This allows `tern` to work with [Polymer](http://polymer-project.org) / [Web Components](http://webcomponents.org) projects!

screen shot 2015-07-20 at 4 57 10 pm

Also, fixed the `acorn` dependency – `tern` works with 1.x, but 2.x was released and is not compatible.

### CODE REVIEW

**Comment by angelozerr** [comment]
Tanks for your PR !

Is It working With webbrowser?

It should be cool if you could 

add test
add an option tout disable It
support baseurl option like requirejs tern plugin

I Will accept your PR next month

**Comment by myfreeweb** [comment]
What should the `baseUrl` option do? Prepend a base path to the `addFile` call? (e.g. `script.js` would add `build/script.js` with `baseURL: 'build'`)?

Also, how do you feel about reformatting all the code to [standard style](http://standardjs.com/)? (Or [semistandard](https://github.com/Flet/semistandard) if you like semicolons) – Right now there's a lot of trailing whitespace all over the place...

**Comment by angelozerr** [comment]
> What should the baseUrl option do?

@myfreeweb forget my comment.

I have commited

**Comment by myfreeweb** [comment]
No, `loadEagerly` is a way to statically list files that are always loaded, how could it be a replacement for discovering files referenced in HTML?
The `node` and `requirejs` plugins use `addFile` to load dependencies.

Why did you close the PR?

**Comment by angelozerr** [comment]
> The `node` and `requirejs` plugins use `addFile` to load dependencies.

Yes you are right, but those plugins create their own scope. In browser-extension, the HTML file has not their own scope (it uses the global scope), so I tell me that `loadEagerly` is enough, no?

> Why did you close the PR?

Sorry for my mistake. Your PR must be resolved because of some conflicts.

**Comment by myfreeweb** [comment]
It's a **static list of files in a JSON config file**. Do *you* want to **edit a list of files every time you add a file**?! Do you want another list of files to even *exist*?

**Comment by angelozerr** [comment]
> It's a static list of files in a JSON config file. 

You can use regexp expression like `**/**.js`, but I agree with you, your solution is more cleaner. But I would like to avoid adding a lot of unknown files (when user is typing). To do that we could use fs.existsSynch (wich will work only for node.js) like https://github.com/marijnh/tern/blob/master/plugin/node.js#L77 and by testing the existing of require in order to the plugin continue to work with webbrowser. What do you think about that?

**Comment by myfreeweb** [comment]
tern [already checks whether the file exists](https://github.com/marijnh/tern/blob/6e998154b3390d22a78f294cf64aeb2fb0161677/lib/tern.js#L120), obviously

**Comment by angelozerr** [comment]
> tern [already checks whether the file exists](https://github.com/marijnh/tern/blob/6e998154b3390d22a78f294cf64aeb2fb0161677/lib/tern.js#L120), obviously

It checks if file was added but not if file exists in the filesystem.

**Comment by myfreeweb** [comment]
Hmm, it really does create empty entries... (╯°□°）╯︵ ┻━┻

**Comment by angelozerr** [comment]
Thanks @myfreeweb !

**Pull request merged**
